apiVersion: v1
kind: Pod
metadata:
  name: book-manager
  labels:
    app: book-manager
spec:
  containers:
  - name: myapp
    image: saikiranchalla/book-manager
    env:
    - name: spring.datasource.url
      value: jdbc:mysql://mysql.default.svc.cluster.local:3306/book_manager
    - name: spring.datasource.username
      value: "root"
    - name: spring.datasource.password
      value: "root"
    ports:
      - containerPort: 8080
