apiVersion: v1
kind: Pod
metadata:
  name: book-manager
  labels:
    name: book-manager
spec:
  containers:
  - name: myapp
    image: saikiranchalla/book-manager
    env:
    - name: spring.datasource.url
      value: jdbc:mysql://mysql.default.svc.cluster.local:3306/book_manager
    - name: server.port
      value: "8080"
    ports:
      - containerPort: 8080
