apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: saikiranchalla/book-manager
        livenessProbe:
            httpGet:
              path: /book
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 30
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://mysql.default.svc.cluster.local:3306/book_manager
        - name: server.port
          value: "8080"
        ports:
          - containerPort: 8080
